use_frameworks!
platform :ios, '11.0'

target 'DependencyExample_Example' do
  pod 'DependencyExample', :path => '../'
  #  pod 'DependencyExample', :git => 'https://github.com/hefgi/DependencyExample.git'

  target 'DependencyExample_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
